Document: googlecl
Title: Debian googlecl Manual
Author: <insert document author here>
Abstract: This manual describes what googlecl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/googlecl/googlecl.sgml.gz

Format: postscript
Files: /usr/share/doc/googlecl/googlecl.ps.gz

Format: text
Files: /usr/share/doc/googlecl/googlecl.text.gz

Format: HTML
Index: /usr/share/doc/googlecl/html/index.html
Files: /usr/share/doc/googlecl/html/*.html

  
